Fix incorrect indentation in test files
Samsung/iotjs-vscode-extension pull request #24
Opened 2018-08-22 08:35 UTC by Yuyupo

We were using 2 or 4 spaces this patch switches it to the 2 space version.

IoT.js-VSCode-DCO-1.0-Signed-off-by: Daniella Barsony bella@inf.u-szeged.hu

2018-08-22 08:47 UTC, robertsipka requested changes

2018-08-22 08:47 UTC, robertsipka commented on src/test/JerryProtocolHandler.test.ts
> +      byteCodeCP: 42,
missing indentation.

2018-08-22 08:47 UTC, robertsipka commented on src/test/JerryProtocolHandler.test.ts
> +    });
These two closing brace should be inside with two spaces.

2018-08-22 08:47 UTC, robertsipka commented on src/test/JerryProtocolHandler.test.ts
> +        ],
You should use indentations here as well.

2018-08-22 08:47 UTC, robertsipka commented on src/test/JerryProtocolHandler.test.ts
> +        byteCodeCP: 42,
missing indentation

2018-08-22 09:57 UTC, Yuyupo commented
@robertsipka Thanks for the review changed it according to what was requested.

2018-08-22 11:08 UTC, robertsipka approved these changes
LGTM

2018-08-22 11:19 UTC, LaszloLango requested changes

2018-08-22 11:19 UTC, LaszloLango commented on src/test/JerryProtocolHandler.test.ts
>        });
wrong indentation

2018-08-22 11:19 UTC, LaszloLango commented on src/test/JerryProtocolHandler.test.ts
> +      test('throws on scriptId 0 with one source', () => {
wrong indentation

2018-08-22 11:19 UTC, LaszloLango commented on src/test/JerryProtocolHandler.test.ts
> +            assert.strictEqual(id, bpAfter.activeIndex);
wrong indentation

2018-08-22 11:19 UTC, LaszloLango commented on src/test/JerryProtocolHandler.test.ts
> +            assert.strictEqual(id, 4);
wrong indetation

2018-08-24 06:48 UTC, Yuyupo commented
@LaszloLango I've updated the PR.

2018-08-24 07:56 UTC, LaszloLango approved these changes
LGTM

2018-08-24 07:56 UTC, merged